### ISSUE TITLE
analizo failing parsing doxyparse output on kdelibs

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#148]

**Comment by motta-tiago** [comment]
Joenio, the problem manifested in the 7f7af640fbb5c36a3a79de66be8bdb0222509a67 git key in kdelibs project.
Thanks

**Comment by motta-tiago** [comment]
Others keys with a same problem in the kdelibs:
54aa10fc089ea9e3c2d180b5f70df7f53c6cc952
ec80efa31106efc09956c1a217ae13b93fb66fea
--
0f4cf41b22bbcbfbb145e1ce3b15ded4e5303c02
c165e4700dc156a20ed793ca72a151a1cd9f5180
d381069cd67459c41826f0ca0ec69f41daada162
71f9f3dec42c21d9d462483d653bd86c06e935d9
d2a27ef497d46598000b395b1102467d25c83639
3b47b2de55e77c987855db5ac7f27cae9442d2be
35386117c0d35c1f9f1d787a46a3d4dcde5ef160
84878fd07c7f5c7806e44cf990e501db295908d5
766a17c876b90eb991619f9c42cc4ec0fd61d56b
92732caed7312d8e51f19eb6d55223b2af29b323

**Comment by joenio** [comment]
kdelibs commit 7f7af640fbb5c36a3a79de66be8bdb0222509a67 is failing reporting the following error:

```
./bin/analizo metrics ../testes/kdelibs/
Subroutine JSON::PP::Boolean::(++ redefined at /usr/share/perl/5.26/overload.pm line 48.
Subroutine JSON::PP::Boolean::(-- redefined at /usr/share/perl/5.26/overload.pm line 48.
Subroutine JSON::PP::Boolean::(0+ redefined at /usr/share/perl/5.26/overload.pm line 48.
YAML::XS::Load Error: The problem:

    found character that cannot start any token

was found at document: 1, line: 813794, column: 9
while scanning for the next token at line: 813794, column: 9
	...propagated at /home/joenio/src/analizo-projects/analizo/lib/Analizo/Extractor/Doxyparse.pm line 48.
```

**Comment by joenio** [comment]
sample of doxyparse output:

```yaml
.../kdelibs/nepomuk/utils/daterange.h:
  "DateRange":
    inherits:
      - @3334::Function
    defines:
      - "end()":
          type: function
          line: 73
          protection: public
          lines_of_code: 4
          parameters: 0
          conditional_paths: 1
          uses:
            - "d":
                type: macro definition
                defined_in: "khtmlfind.cpp"
```
