### ISSUE TITLE
doxyparse 1.8.11 doesn't report dependencies in same file

### ISSUE THREAD

**Issue by joenio** [analizo/analizo#83]
the test below is failing

```
  Scenario: argument versus instance variable
    Given I am in t/samples/printer/<language>
    When I run "analizo graph ."
    Then analizo must report that "Printer1::Printer1(<msg_type>)" depends on "Printer1::message"
    And analizo must report that "Printer2::Printer2(<msg_type>)" depends on "Printer2::message"
    Examples:
      | language | msg_type |
      | cpp      | string       |
      | java     | String       |
```

**Comment by joenio** [comment]
seems a kind of doxygen limitation

**Comment by joenio** [comment]
commit ee52e84d0327b70f21905304627e5bdddcd6ff9d

**Comment by joenio** [comment]
this was resolved on doxygen: https://bugzilla.gnome.org/show_bug.cgi?id=398942

**Comment by Rdlenke** [comment]
I've noticed two different things that could possible be related to this issue.

Doxyparse can't detect member references if we use the "using" directive.

This works:
```cpp
#include <string>

class Main
{
  private:
    std::string word;
  public:
    Main(std::string);
};

Main::Main(std::string w)
{
  this->word = w;
}
```
```
  "Main":
    defines:
      - "Main(std::string)":
          type: function
          line: 8
          protection: public
          lines_of_code: 4
          parameters: 1
          conditional_paths: 1
          uses:
            - "word":
                type: variable
                defined_in: Main
      - "word":
          type: variable
          line: 6
```

But this doesn't.
```cpp
#include <string>

using namespace std;

class Main
{
  private:
    string word;
  public:
    Main(string);
};

Main::Main(string w)
{
  this->word = w;
}
```
```
  "Main":
    defines:
      - "Main(string)":
          type: function
          line: 10
          protection: public
          lines_of_code: 4
          parameters: 1
          conditional_paths: 1
      - "word":
          type: variable
          line: 8
```

Also, the cpp tests do pass if we remove the _using_ directive and explicitly define the namespace.

For the java ones, however, there seems to be other problem. Doxyparse can't detect references to member variables if we use this (even if it was fixed in Doxygen)

```java
public class Main
{
  private String attribute;

  public Main(String a)
  {
    this.attribute = a;
  }
}
```
```
  "Main":
    defines:
      - "Main(String)":
          type: function
          line: 5
          protection: public
          lines_of_code: 4
          parameters: 1
          conditional_paths: 1
      - "attribute":
          type: variable
          line: 3
```

Removing _this_ does make it work. Also, changing the parameter name to the name of the member attribute also fixes the problem.
```java
public class Main
{
  private String attribute;

  public Main(String attribute)
  {
    this.attribute = attribute;
  }
}
```
```
  "Main":
    defines:
      - "Main(String)":
          type: function
          line: 5
          protection: public
          lines_of_code: 4
          parameters: 1
          conditional_paths: 1
          uses:
            - "attribute":
                type: variable
                defined_in: Main
      - "attribute":
          type: variable
          line: 3
```

Seems to be doxygen related. I will try to create an example using doxyapp and open an issue in bugzilla.
