### ISSUE TITLE
Wrong cyclomatic complexity return when C code has a ternary conditional operator

### ISSUE THREAD

**Issue by luanguimaraesla** [analizo/analizo#91]
Cyclomatic complexity analisis fails for some ternary operator examples like:
```
void example() {
	char var = something ? 'a' : (anotherthing ? 'b' : 'c' );
	printf("%c\n", var);
}
```
It returns 1, but the expected return is 3 according to the following definition of Cyclomatic Complexity metric:

_"[...] The cyclomatic complexity of a graph can be calculated using a formula of 
graph theory:  `v(G) = e - n + 2`  where `e` is the number of edges and `n` is the number of nodes of the graph."_

Article _Monitoring of source code metrics in open source projects_ by Paulo Roberto Miranda Meirelles.

It's propably a limitation of **Doxyparse**

**Comment by arkye** [comment]
A MR was attempted with the case tests in order to evaluate the agreement of the CC Analysis. Unfortunately, the MR does not comply with the standards of MR and will be closed. A patch with the implementation of the case tests is attached below.

[cc.patch.txt](https://github.com/analizo/analizo/files/987881/cc.patch.txt)

**Comment by Rdlenke** [comment]
This is a limitation of Doxyparse. It doesn't seem to know that ternary operators create conditional paths.

```c
#include <stdio.h>

int main() 
{
    1 > 0 ? printf("yes") : printf("no");

    return 0;
}
```

```
  "main.c":
    defines:
      - "main()":
          type: function
          line: 3
          protection: public
          lines_of_code: 6
          parameters: 0
          conditional_paths: 1
```

```c
#include <stdio.h>

int main() 
{
    if(1 > 0) 
    {
        printf("yes");
    }
    else {
        printf("no");
    }
    
    return 0;
}
```

```
  "main.c":
    defines:
      - "main()":
          type: function
          line: 3
          protection: public
          lines_of_code: 12
          parameters: 0
          conditional_paths: 2
```

Could be related to Doxygen.
